# Use the official Amazon Corretto 22 JDK image as the base image
FROM amazoncorretto:22-alpine

# Set the working directory in the container
WORKDIR /app

# Create a volume at /tmp
VOLUME /tmp

# Copy the JAR file into the container
COPY target/NotificationService-0.0.1-SNAPSHOT.jar app.jar

# Expose port 8080 to the outside world
EXPOSE 8080

# Define the command to run the application
CMD ["java", "-jar", "app.jar"]
